{% set name = "ukbparse" %}
{% set version = "0.16.0" %}
{% set sha256 = "768b3de1ee1caf7df0f8354fd685c5180bfd85d3846a1df30afd6285869e422d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - ukbparse                = ukbparse.main:main
    - ukbparse_join           = ukbparse.scripts.join:main
    - ukbparse_compare_tables = ukbparse.scripts.compare_tables:main
    - ukbparse_htmlparse      = ukbparse.scripts.htmlparse:main
    - ukbparse_demo           = ukbparse.scripts.demo:main

requirements:
  build:
    - python
    - pip
  run:
    - python >=3.5
    - h5py
    - numpy
    - pandas
    - pyparsing
    - six
    - pytables
    - beautifulsoup4
    - lxml
    - libxml2

test:
  source_files:
    - ukbparse/tests
  requires:
    - pip
    - coverage
    - pytest
    - pytest-cov
    - jinja2
    - notebook
    - jupyter
    - pygments

  commands:
    # bash_kernel is not available on
    # conda, but is imported by the
    # ukbparse.scripts.demo module
    - pip install bash_kernel
    - ukbparse -V
    - ukbparse_join
    - ukbparse_compare_tables
    - ukbparse_htmlparse
    - pytest -v --cov=ukbparse ukbparse/tests -k "not (lowMemory or HDF or test_demo)"


about:
  home: https://git.fmrib.ox.ac.uk/fsl/ukbparse/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'The FSL Python library'
  dev_url: https://git.fmrib.ox.ac.uk/fsl/ukbparse/

extra:
  recipe-maintainers:
    - pauldmccarthy
