travis:
  secure:
    BINSTAR_TOKEN: YyepBTsMb/rFAg3zaJQe17PSXbf8Ryq1VvACFmx6QCrnSgKUegslhl9V8/V3MSdMawYpnaYscZNVrZwJB+qUgu/mx8dPZDLrmEF1cPjqCX7uz5m7sEBxcORsF5XQKDXwBP3PNLnAkBR+kgqXv7XvhA8GZ4bEy+jAh1Xnvk61Azs8efgL31zOIJ7d1eAua/D9a+BlSduGQltE0/pjfd40o/et/FUvGSZSGwLc66ThGZ04//64N5ZzsjdWVl0BLLEWdEnhGk2YIGzrN49vZUvpGWJdS357wqx93w/4KSM+biZDJwyqu/pFGiVw4YwonHTFWYyxbyboiUiPpsgR/5v9xGelCnfvYsW7viRmyn7E3OWBhWS4VX+QMMaGPA4wBaUCrV4+VZlnt9xOk80F+GLbZkjlUp0kPc3ctqP41BOQV0EnZgmTi8j1/tx5gF3Ws0KKDsSh3KWciU7la8HaEwJfDj4bvYjDy1cELANC+avzFzMZoZetbEtiU+k7SK4h0LxsIAKdgOzjZ/fimtAu6RPrychuBZqokLG4mGJ/mskQfGtYsRZBImlMveR8syPt2XxcipADwgu+6At6RHO3ry0O+aXAZZ3KdopsnQgNJMa373P233nA39V23j9rOm4jeeW4QPH89vAJt46NBYyLNuHic8+HhNioIPAPhgJFw5fA3ww=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
